[debug] [2020-04-07T09:50:53.667Z] ----------------------------------------------------------------------
[debug] [2020-04-07T09:50:53.669Z] Command:       /home/simba/.nvm/versions/node/v13.12.0/bin/node /usr/local/bin/firebase init functions
[debug] [2020-04-07T09:50:53.670Z] CLI Version:   8.0.2
[debug] [2020-04-07T09:50:53.670Z] Platform:      linux
[debug] [2020-04-07T09:50:53.670Z] Node Version:  v13.12.0
[debug] [2020-04-07T09:50:53.678Z] Time:          Tue Apr 07 2020 11:50:53 GMT+0200 (Central Africa Time)
[debug] [2020-04-07T09:50:53.678Z] ----------------------------------------------------------------------
[debug] [2020-04-07T09:50:53.678Z] 
[debug] [2020-04-07T09:50:53.688Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-07T09:50:53.716Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-07T09:51:01.970Z] ----------------------------------------------------------------------
[debug] [2020-04-07T09:51:01.973Z] Command:       /home/simba/.nvm/versions/node/v13.12.0/bin/node /usr/local/bin/firebase init functions
[debug] [2020-04-07T09:51:01.973Z] CLI Version:   8.0.2
[debug] [2020-04-07T09:51:01.973Z] Platform:      linux
[debug] [2020-04-07T09:51:01.973Z] Node Version:  v13.12.0
[debug] [2020-04-07T09:51:01.974Z] Time:          Tue Apr 07 2020 11:51:01 GMT+0200 (Central Africa Time)
[debug] [2020-04-07T09:51:01.974Z] ----------------------------------------------------------------------
[debug] [2020-04-07T09:51:01.974Z] 
[debug] [2020-04-07T09:51:01.981Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-07T09:51:01.995Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
